### PR TITLE
More dox

### PR DESCRIPTION
**Pull request by okawo80085**
Fixed build issues and added new info on animations

### CODE REVIEW

**Comment by SimLeek** [comment]
Looks good afaik. Haven't tested compiling.

**Comment by okawo80085** [comment]
Well, test the build then xD

**Comment by okawo80085** [comment]
It should be building fine, but then again, i could've missed something

**Comment by SimLeek** [comment]
alright, fine

**Comment by SimLeek** [comment]
Compiled, can follow all the links, looks good.

**Comment by okawo80085** [comment]
Great, merging it.

**Pull request merged**
